routes/web.php
<?php

// use ImageOptimizer;

use App\Area;
use App\carts;
use App\Discount;

Route::get('/', function () {
    return view('welcome');
});
Route::get('/contact', function () {
    return view('contact');
})->name('contact') ; 


Route::get('/about', function () {
    return view('about');
})->name('about') ;


  //  language change
  Route::get('change-language/{lang}' , function($lang){
    
    App::setLocale($lang);

    session()->put('locale', $lang);

    if(session('locale') == 'ar'){

        $_SESSION['language'] = 'arabic' ;
    }else{
        $_SESSION['language'] = 'english' ;

    }
    return redirect()->back();

    
} ) ->name ('change-language') ;


Route::get('email', function () {

    $orderstatus = App\orderstatuses::find(38);
    $shipping = App\shippings::first();
    // , , 'shipping' => $shipping
    return view('emails.order_status' , ['msg' => 'Hello World' , 'order' => $orderstatus  ] );
})->name('email') ;


Route::get('/product', 'ProductsController@showProducts' )->name('product') ;

Route::get('/gallery', 'GalleriesController@showGalleryImages' )->name('gallery') ;

// Route::get('/product', function () {
//     return view('product');
// });
Route::get('/userlogin', function () {


    // dd(url()->previous());

    if(isset($_SESSION['logged_in'])){
        return redirect()->back()->with('error' , 'Already Logged in');
    }
    if(strpos( url()->previous() ,  'checkout') ){
        session()->put('checkout' , 'checkout');
    }

    return view('userlogin');

})->name('userlogin') ;
Route::get('/signup', function () {

    if(isset($_SESSION['logged_in'])){
        return redirect()->back()->with('error' , 'Already Logged in');
    }

    if(strpos( url()->previous() ,  'checkout') ){
        session()->put('checkout' , 'checkout');
    }
    $areas = Area::all();
    return view('signup' , compact('areas'));
});


Route::get('reset/password','RegusersController@resetEmailPassword')->name('reset.password');
Route::post('send-reset-password-link','RegusersController@sentPasswordResetLink')->name('send-reset-password-link');

Route::post('save-new-password','RegusersController@sentNewPassword')->name('save-new-password');


Route::get('password/reset/{email}/token/{token}','RegusersController@resetPassword')->name('password.reset.token');


Route::get('edit-profile' , 'RegusersController@editProfile')->name('edit-profile');


if(!isset($_SESSION)) 
{ 
    session_start(); 
}
use App\products;
use App\regusers;
use App\shippings;
use Carbon\Carbon;
use App\contactuses;
use App\orderstatuses;
use App\Jobs\SendDiscountMail;
use App\Jobs\SendCustomerEmail;
use App\Jobs\SendCustomerEmailCheck;
use Illuminate\Support\Facades\Route;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Artisan;
use Spatie\ImageOptimizer\OptimizerChainFactory;

Route::get('/checkout', "CheckoutController@viewCart" )->name('checkout') ;
Auth::routes();

Route::get('/home', 'AbcController@index')->middleware('auth');
Route::get('/header', 'HeaderController@index')->name('header');
Route::get('/aside', 'AsideController@index')->name('aside');
Route::resource('homes','HomeController')->middleware('auth');
Route::resource('categories','CategoriesController')->middleware('auth');
Route::get('/manage-category', 'CategoriesController@approve')->name('category');
Route::resource('products','ProductsController')->middleware('auth');

Route::get('products/exports/{ids}','ProductsController@exportProducts')->name('products.exports');

Route::get('/manage-products', 'ProductsController@approve')->name('products');
Route::resource('aboutuses','AboutusesController')->middleware('auth');
Route::resource('contactuses','ContactusesController')->middleware('auth');
Route::resource('orders','OrdersController')->middleware('auth');
Route::resource('homepages','HomepagesController')->middleware('auth');
Route::resource('galleries','GalleriesController')->middleware('auth');
Route::resource('shippings','ShippingsController')->middleware('auth');
Route::resource('areas','AreaController')->middleware('auth');
Route::get('areas/delete/{id}','AreaController@destroy')->name('areas.delete') ->middleware('auth');

Route::resource('regusers','RegusersController');

Route::post('guest-signup' ,'RegusersController@guestSignup' )->name('guest-signup') ;
Route::get('guest-signup' ,'RegusersController@guestSignup' )->name('guest-signup') ;

Route::get('reguser/{user}/orders','RegusersController@viewOrders')->name('reguser-orders');


Route::get('filter-users' , 'RegusersController@filter' )->name('filter-users') ;
Route::get('/export-customers/{ids}', 'RegusersController@exportCustomers')->name('export-customers');

Route::resource('carts','CartsController');
Route::resource('productsections','ProductsectionsController')->middleware('auth');
Route::get('/user-login', 'RegusersController@login')->name('orders');
Route::get('/user-logout', 'RegusersController@logout')->name('orders');
Route::get('/contact-form', 'ContactFormController@store')->name('orders');

Route::get('/carts', 'CartsController@store')->name('carts');
Route::get('/update-cart-quantity', 'CartsController@updateCartQuantity')->name('update-cart-quantity');

Route::get('/update-cart-quantity-ajax/{cart_id}/{quantity}', 'CartsController@updateCartQuantityAjax')->name('update-cart-quantity-ajax');

Route::post('register-guest', 'RegusersController@guestSignupStore')->name('register-guest') ;

Route::post('/order-cart', 'OrderstatusesController@store')->name('orderstatuses');
Route::get('/order-cart', 'OrderstatusesController@store')->name('orderstatuses');

Route::get('/sadad-payment', 'OrderstatusesController@sadadPayment')->name('sadad-payment');

Route::get('/sadad-payment-success', 'OrderstatusesController@sadadPaymentSuccess')->name('sadad-payment-success');

Route::post('/sadad-payment-success', 'OrderstatusesController@sadadPaymentSuccess')->name('sadad-payment-success');


Route::get('paymentsuccess', 'OrderstatusesController@payment_success');
Route::get('paymenterror', 'OrderstatusesController@payment_error');

Route::get('/delete-cart', 'CartsController@delete')->name('carts');
Route::resource('admins','AdminsController')->middleware('auth');

Route::get('/contact-form','ContactFormController@create');
Route::post('/contact-form','ContactFormController@store');
Route::post('/user-logout','RegusersController@logout');
Route::post('/user-login', 'RegusersController@login');
// Route::get('/product-category', 'ProductsController@show1')->name('products');
Route::get('/product-category', 'ProductsController@showCategoryProducts')->name('products');

Route::get('/gallery-images', 'GalleriesController@showGallery')->name('gallery-images');

Route::get('/order-history', 'OrdersController@showHistory')->name('order-history');
Route::get('/order-history/{order}/details', 'OrdersController@showOrderDetails')->name('order-history.details');

Route::resource('orderstatuses','OrderstatusesController')->middleware('auth');

Route::get('/export-orders/{ids}', 'OrderstatusesController@exportOrders')->name('export-orders');

Route::get('/export-orders-products/{ids}', 'OrderstatusesController@exportOrdersProducts')->name('export-orders-products');

Route::get('/export-order/{id}', 'OrderstatusesController@exportOrder')->name('export-order');
Route::get('/export-invoice/{id}', 'OrderstatusesController@exportInvoice')->name('export-invoice');

Route::get('/order-filter', 'OrderstatusesController@search')->name('orderstatuses');

Route::get('/product-filter', 'OrderstatusesController@search1')->name('orderstatuses');
Route::resource('first','FirstController');

Route::get('manage-discounts' , 'DiscountController@index')->name('manage-discounts');
Route::post('update-discounts' , 'DiscountController@update')->name('update-discounts');

Route::get('gift-discount/{customer}' , 'DiscountController@giftDiscount')->name('gift-discount');
Route::get('remove-discount/{customer}' , 'DiscountController@removeDiscount')->name('remove-discount');

// dropzone images
Route::post('/images-save', 'GalleriesController@saveDropzoneImage')->name('images-save') ;
Route::get('/images-delete/{id}', 'GalleriesController@deleteDropzoneImage');








Route::post('/update-category-order', 'CategoriesController@updateOrder') ;

Route::post('/update-product-order', 'ProductsController@updateOrder') ;

// Route::get('test', function(){
//     // return view('layouts.main');
//     $orderstatuses = orderstatuses::latest()->first();
    
//     $customer = regusers::where('id' ,$orderstatuses->cid )->get();

//     $message = 'Dear '. $orderstatuses->customer->full_name.', we have received order # ' . $orderstatuses->id .' and are working on it now.<br></p><p style="color: #242424;">We will email you an update when we have delivered it.<br>';

//     $subject = 'Your vQuick Order is submitted';

//     dispatch(new SendCustomerEmail($customer , $message , $subject , $orderstatuses ));

// });

Route::get('email-test' , function(){

    $order = orderstatuses::latest()->first();

    $customer = regusers::where('id' ,$order->cid )->get();

    $message = 'Dear '. $order->customer->full_name.', we have received order # ' . $order->id .' and are working on it now.<br></p><p style="color: #242424;">We will email you an update when we have delivered it.<br>';

    $subject = 'Your vQuick Order is submitted';

    dispatch(new SendCustomerEmailCheck($customer , $message , $subject , $order ));
    echo "Email is dispatched  " . Carbon::now();
} );

Route::get('start-queue' , function(){
    Artisan::call("queue:restart");
    Artisan::call("queue:work");    
});


Route::get('invoice/{id}', function($id){

    $order = orderstatuses::find( $id );
    $msg = 'message';
    // return view('pdf.invoice' , compact('order' , 'msg') );
    return view('pdf.pdf_invoice2' , compact('order' , 'msg') );
});

Route::get('payment_success', function(){
    // return view('payment_success');
});

resources/views/orderstatuses/create.blade.php
@extends('orders.layout')
@section('content')
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="pull-left">
        <h2>Add New Orders</h2>
      </div>
      <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('orders.index') }}"> Back</a>
      </div>
    </div>
  </div>
      
  @if ($errors->any())
  <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
      <ul>
        @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
  @endif

  

  <form action="{{ route('orders.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    
    <div class="row" style="width:80%;margin:auto;">   

      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Order Number:</strong>
          <input type="text" class="form-control" name="order_number" placeholder="Enter Order Number" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Payment Status:</strong>
          <select class="form-control" name="payment_method">
            <option value="cash">Cash on delivery</option>
            <option value="paid">Paid</option>
          </select>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Quantity:</strong>
          <input type="text" class="form-control" name="quantity" placeholder="Enter Quantity" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Available:</strong>
          <input type="text" class="form-control" name="available" placeholder="Enter  Available" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Status:</strong>
          <select class="form-control" name="status">
            <option value="cash">Pending</option>
            <option value="paid">Confirmed</option>
            <option value="out for delivery">Out for Delivery</option>
            <option value="delivered">Delivered</option>
            <option value="cancelled">Cancelled</option>
          </select>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Full Name:</strong>
          <input type="text" class="form-control" placeholder="Enter Full Name" name="full_name" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Address:</strong>
          <input type="text" class="form-control" placeholder="Enter Address" name="address" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Date Time:</strong>
          <input type="date" class="form-control" name="date" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Product Name:</strong>
          <select class="form-control" name="product_name">
            <option selected disabled>Select Product</option>
            <?php use App\products;
              $products = products::all(); ?>
              @foreach ($products as $product)
                <option value="{{ $product->name}}">{{ $product->name}}</option>
              @endforeach
          </select>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>    
  </form>
  @endsection

resources/views/orderstatuses/edit.blade.php
@extends('orderstatuses.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Orders</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('orderstatuses.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('orderstatuses.update', $orderstatus->id) }}" method="POST">
      @csrf
      @method('PUT')

      <div class="row" style="width:80%;margin:auto;">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <strong>Total Price:</strong>
            <input type="text" class="form-control" value="{{ $orderstatus->total_price }}" name="total_price" readonly />
          </div>
        </div>
        <?php $a=0;
        if( $orderstatus->payment_method == 'pending') {
          $a="paid";
        } else {
          $a="pending";
        }?>
        <div class="col-xs-12 col-sm-12 col-md-12"  >
          <div class="form-group" id="payment_method" >
            <strong>Payment Status:</strong>
            <select class="form-control" name="payment_method">
              <option value="pending" @if($orderstatus->payment_method ==  'pending' )  selected @endif >pending</option>
              <option value="paid" @if($orderstatus->payment_method == 'paid'  ) selected @endif  >paid</option>
            </select>
          </div>
        </div>
    
        <div class="col-xs-12 col-sm-12 col-md-12" >
          <div class="form-group"  >
            <strong>Status:</strong>
            <select class="form-control" name="status" id="status">
              {{--  <option value="{{ $orderstatus->status }}">{{ $orderstatus->status }}</option>  --}}
              {{--  <option value="" > Change Status </option>  --}}
              <option value="pending" @if($orderstatus->status == 'pending' ) selected @endif >pending</option>
              <option value="confirmed" @if($orderstatus->status == 'confirmed' ) selected @endif >confirmed</option>
              <option value="out for delivery" @if($orderstatus->status == 'out for delivery' ) selected @endif >out for delivery</option>
              <option value="delivered" @if($orderstatus->status == 'delivered' ) selected @endif >delivered</option>
              <option value="cancelled" @if($orderstatus->status == 'cancelled' ) selected @endif >cancelled</option>
            </select>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
   
    </form>


@endsection

resources/views/orderstatuses/index.blade.php
@extends('orderstatuses.layout') 
@section('content')


<style>
  .badge-danger{
    background-color: red;
    color:white;
  }
  .badge-success{

  }
  .badge-primary{

  }
  .badge-warning{

  }
  .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th{
    padding: 6px !important;
  }

  .pending{
    background-color:#d9534f;
  }

  .paid{
    background-color:#2d995b;
  }
</style>

    <?php use App\regusers;?>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <form action="/order-filter" method="GET">
    @csrf
			<div class="col-12" style="display:grid;grid-template-columns: 20% 20% 20% 20%;grid-column-gap:3%;">
				<div class="form-group">
					<input type="text" class="form-control" @if(isset($filters) && isset($filters['search_order_number'])) value="{{$filters['search_order_number']}}" @endif name="search_order_number" placeholder="Search Order Number">
				</div>
				<div class="form-group">
           
          <input type="text" class="form-control" name="name"  @if(isset($filters) && isset($filters['name'])) value="{{$filters['name']}}" @endif placeholder="Customer Name">

        </div>
        
        <div class="form-group">
          <select class="form-control" name="search_payment_status">
            <option selected disabled>Payment Status</option>
            <option value="pending" @if(isset($filters['search_payment_status']) && $filters['search_payment_status'] == 'pending' ) selected @endif >pending</option>
            <option value="paid" @if(isset($filters['search_payment_status']) && $filters['search_payment_status'] == 'paid' ) selected @endif >Paid</option>
          </select>
				</div>
        <div class="form-group">
          <select class="form-control" name="status">
            <option selected disabled>Status</option>
            <option value="pending" @if(isset($filters['status']) && $filters['status'] == 'pending' ) selected @endif >Pending</option>
            <option value="confirmed"  @if(isset($filters['status']) && $filters['status'] == 'confirmed' ) selected @endif >Confirmed</option>
            <option value="out for delivery"  @if(isset($filters['status']) && $filters['status'] == 'out for delivery' ) selected @endif >Out for Delivery</option>
            <option value="delivered"  @if(isset($filters['status']) && $filters['status'] == 'delivered' ) selected @endif >Delivered</option>
            <option value="cancelled"  @if(isset($filters['status']) && $filters['status'] == 'cancelled' ) selected @endif >Cancelled</option>
          </select>
        </div>
        
	
        <div class="form-group">
          <select class="form-control" name="payment_method">
            <option value="" > Payment Method </option>
            <option value="cash on delivery"  @if(isset($filters['payment_method']) && $filters['payment_method'] == 'cash on delivery' ) selected @endif  > Cash On Delivery </option>
            <option value="sadad"  @if(isset($filters['payment_method']) && $filters['payment_method'] == 'sadad' ) selected @endif  > Sadad </option>
            </select>
        </div>
        
        <div class="form-group">
          <input type="date" name="lower_date" class="form-control"  @if(isset($filters) && isset($filters['lower_date'])) value="{{$filters['lower_date']}}" @endif style="line-height: 1.375rem;" />
        </div>
        <div class="form-group">
          <input type="date" name="upper_date" class="form-control"  @if(isset($filters) && isset($filters['upper_date'])) value="{{$filters['upper_date']}}" @endif style="line-height: 1.375rem;" />
        </div>
        <div class="form-group">
					<button type="submit" class="btn btn-primary">Search</button>
          <a class="btn btn-danger" href="{{route('orderstatuses.index')}}">X Clear</a>
        </div>
			</div>
    </form>

    @php
        if(isset($filtered_orders)){
          $orderstatuses = $filtered_orders;
        }
    @endphp
    <a class="btn btn-success float-right mb-2" href="{{route('export-orders' , json_encode($orderstatuses->pluck('id')->toArray()) )}}" >Export Orders</a>

    <a class="btn btn-success float-right mb-2 mr-3" href="{{route('export-orders-products' , json_encode($orderstatuses->pluck('id')->toArray()) )}}" >Export Products Report</a>
    
    
    <table class="table table-bordered table-responsive-sm">
        <tr>
          <th>Order Number</th>
          <th>Customer Name</th>
          <th>Payment Status</th>
          <th>Payment Method</th>
          <th>Transaction Number</th>
          <th>Status</th>
          <th>Mobile Number</th>
          <th>Address</th>
          <th>Shipping Area</th>
          <th>Shipping Charges</th>
          <th>Total Price</th>
          <th>Discounted Price</th>
          <th>Date Time</th>
          <th width="280px">Action</th>
        </tr>
        
        @foreach ($orderstatuses as $orderstatus)
        
        @if(!($orderstatus->payment_method == 'sadad' && $orderstatus->payment_status == 'pending'))
        <tr>
          <td>{{ $orderstatus->id }}

            @if($orderstatus->discount_availed == 1)
            <img src="{{asset('files/important.png')}}" style="width:20px; height:auto" >
            @endif


          </td>

          <td>{{ $orderstatus->customer->full_name ?? '' }}</td>

          <td> <label class="label  {{ $orderstatus->payment_status }}" >{{ ucwords($orderstatus->payment_status) }}</label> </td>

          <td>{{ $orderstatus->payment_method }}</td>

          <td>{{ $orderstatus->transaction_number }}</td>

          <td>
            @if($orderstatus->status == 'pending')
            <span class="label label-danger">Pending</span>
            
            @elseif($orderstatus->status == 'confirmed')

            <span class="label label-primary">Confirmed</span>
            
            @elseif($orderstatus->status == 'out for delivery')
            
            <span class="label label-warning">Out For Delivery</span>
            
            @elseif($orderstatus->status == 'delivered')
            
            <span class="label label-success">Delivered</span>

            @elseif($orderstatus->status == 'cancelled')
            
            <span class="label label-danger">Cancelled</span>
            
            @endif
          
          </td>
          <?php $cid=$orderstatus->cid;
          $regusers = regusers::all()->where('id',$cid); ?>
          {{--  @foreach ($regusers as $reguser)
          <?php $cname=$reguser->full_name;
          $caddress=$reguser->address;
          $czone=$reguser->zone;
          $cstreet=$reguser->street;
          $cbuilding=$reguser->building;
          $cdate=$reguser->created_at; ?>
          @endforeach  --}}
          {{--  <!--<td>Building: {{ $cbuilding }}, Street: {{ $cstreet }}, Zone: {{ $czone }}, {{ $caddress }} </td>-->  --}}
          
          <td>{{ $orderstatus->customer->phone ?? '' }}</td>

          <td>{{ $orderstatus->customer->address ?? '' }}</td>

          <td> {{ $orderstatus->area ? $orderstatus->area->area : "" }}</td>
          
          <td> @if($orderstatus->shipping_charges) {{ $orderstatus->shipping_charges }} QTR @endif</td>
          
          
        <td>{{ $orderstatus->carts->count() > 0 ? array_sum($orderstatus->carts->pluck('original_price')->toArray()) +  $orderstatus->charges : '' }} QTR </td> 
        
        
        <td>{{ $orderstatus->total_price }} QTR</td>


          <td>{{ $orderstatus->created_at }}</td>

          <td>
            <form id="delete-form-{{$orderstatus->id}}" action="{{ route('orderstatuses.destroy',$orderstatus->id) }}" method="POST">
              <a class="btn btn-sm btn-info" href="{{ route('orderstatuses.show',$orderstatus->id) }}">View</a>
              <a class="btn btn-sm btn-primary" href="{{ route('orderstatuses.edit',$orderstatus->id) }}">Edit</a>

              
              @csrf
              @method('DELETE')
              {{--  <button type="submit" class="btn  btn-danger">Delete</button>  --}}
              <button type="button" onclick="ask_delete({{$orderstatus->id}})" class="btn btn-sm btn-danger">Delete</button>
            </form>

            <a class="btn btn-sm btn-warning" href="{{ route('export-invoice' , $orderstatus->id) }}"><i class="fa fa-print"></i> </a>


          </td>
        </tr>
        @endif
        @endforeach
    </table>

    @if(
    $orderstatuses instanceof \Illuminate\Pagination\Paginator ||
    $orderstatuses instanceof Illuminate\Pagination\LengthAwarePaginator
  )

    {{$orderstatuses->links() ?? ''}}
@endif



@endsection



@section('scripts')

<script>
  
</script>

@endsection

resources/views/orderstatuses/layout.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>VQuick | Dashboard</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{{asset('css/app.css')}}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    @include('/header');
    @include('/aside');
    <div class="content-wrapper">
        <section class="content-header">
            <h1 style="float:left;">
                Orders
            </h1>
        </section>
        <div style="padding:5%;">
            @yield('content')
        </div>
    </div>
    <footer class="main-footer">
        <strong>Copyright &copy; 2020 <a href="#">vQuick</a>.</strong> All rights reserved.
    </footer>
</div>



<script src="{{asset('js/app.js')}}"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<script>
    function ask_delete(id){
        
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
          }).then((result) => {
            if (result.value) {
                $('#delete-form-'+id).submit();
            }
          });   
    }

    
        $(document).ready(function(){
          var payment_method = '{{$orderstatus->payment_method ?? null}}';

            $('#status').on('change' , function(){

                if($('#status').val() == 'delivered' && payment_method !== 'sadad' ){
                  $('#payment_method').show();

                }else{
                  $('#payment_method').hide();
                }
              });
            });
  
    
        $(document).ready(function(){
                if($('#status').val() == 'delivered'){
                  $('#payment_method').show();
                }else{
                  $('#payment_method').hide();
                }
            });
  

</script>

@yield('scripts')

</body>
</html>