routes/web.php
<?php

// use ImageOptimizer;

use App\Area;
use App\carts;
use App\Discount;

Route::get('/', function () {
    return view('welcome');
});
Route::get('/contact', function () {
    return view('contact');
})->name('contact') ; 


Route::get('/about', function () {
    return view('about');
})->name('about') ;


  //  language change
  Route::get('change-language/{lang}' , function($lang){
    
    App::setLocale($lang);

    session()->put('locale', $lang);

    if(session('locale') == 'ar'){

        $_SESSION['language'] = 'arabic' ;
    }else{
        $_SESSION['language'] = 'english' ;

    }
    return redirect()->back();

    
} ) ->name ('change-language') ;


Route::get('email', function () {

    $orderstatus = App\orderstatuses::find(38);
    $shipping = App\shippings::first();
    // , , 'shipping' => $shipping
    return view('emails.order_status' , ['msg' => 'Hello World' , 'order' => $orderstatus  ] );
})->name('email') ;


Route::get('/product', 'ProductsController@showProducts' )->name('product') ;

Route::get('/gallery', 'GalleriesController@showGalleryImages' )->name('gallery') ;

// Route::get('/product', function () {
//     return view('product');
// });
Route::get('/userlogin', function () {


    // dd(url()->previous());

    if(isset($_SESSION['logged_in'])){
        return redirect()->back()->with('error' , 'Already Logged in');
    }
    if(strpos( url()->previous() ,  'checkout') ){
        session()->put('checkout' , 'checkout');
    }

    return view('userlogin');

})->name('userlogin') ;
Route::get('/signup', function () {

    if(isset($_SESSION['logged_in'])){
        return redirect()->back()->with('error' , 'Already Logged in');
    }

    if(strpos( url()->previous() ,  'checkout') ){
        session()->put('checkout' , 'checkout');
    }
    $areas = Area::all();
    return view('signup' , compact('areas'));
});


Route::get('reset/password','RegusersController@resetEmailPassword')->name('reset.password');
Route::post('send-reset-password-link','RegusersController@sentPasswordResetLink')->name('send-reset-password-link');

Route::post('save-new-password','RegusersController@sentNewPassword')->name('save-new-password');


Route::get('password/reset/{email}/token/{token}','RegusersController@resetPassword')->name('password.reset.token');


Route::get('edit-profile' , 'RegusersController@editProfile')->name('edit-profile');


if(!isset($_SESSION)) 
{ 
    session_start(); 
}
use App\products;
use App\regusers;
use App\shippings;
use Carbon\Carbon;
use App\contactuses;
use App\orderstatuses;
use App\Jobs\SendDiscountMail;
use App\Jobs\SendCustomerEmail;
use App\Jobs\SendCustomerEmailCheck;
use Illuminate\Support\Facades\Route;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Artisan;
use Spatie\ImageOptimizer\OptimizerChainFactory;

Route::get('/checkout', "CheckoutController@viewCart" )->name('checkout') ;
Auth::routes();

Route::get('/home', 'AbcController@index')->middleware('auth');
Route::get('/header', 'HeaderController@index')->name('header');
Route::get('/aside', 'AsideController@index')->name('aside');
Route::resource('homes','HomeController')->middleware('auth');
Route::resource('categories','CategoriesController')->middleware('auth');
Route::get('/manage-category', 'CategoriesController@approve')->name('category');
Route::resource('products','ProductsController')->middleware('auth');

Route::get('products/exports/{ids}','ProductsController@exportProducts')->name('products.exports');

Route::get('/manage-products', 'ProductsController@approve')->name('products');
Route::resource('aboutuses','AboutusesController')->middleware('auth');
Route::resource('contactuses','ContactusesController')->middleware('auth');
Route::resource('orders','OrdersController')->middleware('auth');
Route::resource('homepages','HomepagesController')->middleware('auth');
Route::resource('galleries','GalleriesController')->middleware('auth');
Route::resource('shippings','ShippingsController')->middleware('auth');
Route::resource('areas','AreaController')->middleware('auth');
Route::get('areas/delete/{id}','AreaController@destroy')->name('areas.delete') ->middleware('auth');

Route::resource('regusers','RegusersController');

Route::post('guest-signup' ,'RegusersController@guestSignup' )->name('guest-signup') ;
Route::get('guest-signup' ,'RegusersController@guestSignup' )->name('guest-signup') ;

Route::get('reguser/{user}/orders','RegusersController@viewOrders')->name('reguser-orders');


Route::get('filter-users' , 'RegusersController@filter' )->name('filter-users') ;
Route::get('/export-customers/{ids}', 'RegusersController@exportCustomers')->name('export-customers');

Route::resource('carts','CartsController');
Route::resource('productsections','ProductsectionsController')->middleware('auth');
Route::get('/user-login', 'RegusersController@login')->name('orders');
Route::get('/user-logout', 'RegusersController@logout')->name('orders');
Route::get('/contact-form', 'ContactFormController@store')->name('orders');

Route::get('/carts', 'CartsController@store')->name('carts');
Route::get('/update-cart-quantity', 'CartsController@updateCartQuantity')->name('update-cart-quantity');

Route::get('/update-cart-quantity-ajax/{cart_id}/{quantity}', 'CartsController@updateCartQuantityAjax')->name('update-cart-quantity-ajax');

Route::post('register-guest', 'RegusersController@guestSignupStore')->name('register-guest') ;

Route::post('/order-cart', 'OrderstatusesController@store')->name('orderstatuses');
Route::get('/order-cart', 'OrderstatusesController@store')->name('orderstatuses');

Route::get('/sadad-payment', 'OrderstatusesController@sadadPayment')->name('sadad-payment');

Route::get('/sadad-payment-success', 'OrderstatusesController@sadadPaymentSuccess')->name('sadad-payment-success');

Route::post('/sadad-payment-success', 'OrderstatusesController@sadadPaymentSuccess')->name('sadad-payment-success');


Route::get('paymentsuccess', 'OrderstatusesController@payment_success');
Route::get('paymenterror', 'OrderstatusesController@payment_error');

Route::get('/delete-cart', 'CartsController@delete')->name('carts');
Route::resource('admins','AdminsController')->middleware('auth');

Route::get('/contact-form','ContactFormController@create');
Route::post('/contact-form','ContactFormController@store');
Route::post('/user-logout','RegusersController@logout');
Route::post('/user-login', 'RegusersController@login');
// Route::get('/product-category', 'ProductsController@show1')->name('products');
Route::get('/product-category', 'ProductsController@showCategoryProducts')->name('products');

Route::get('/gallery-images', 'GalleriesController@showGallery')->name('gallery-images');

Route::get('/order-history', 'OrdersController@showHistory')->name('order-history');
Route::get('/order-history/{order}/details', 'OrdersController@showOrderDetails')->name('order-history.details');

Route::resource('orderstatuses','OrderstatusesController')->middleware('auth');

Route::get('/export-orders/{ids}', 'OrderstatusesController@exportOrders')->name('export-orders');

Route::get('/export-orders-products/{ids}', 'OrderstatusesController@exportOrdersProducts')->name('export-orders-products');

Route::get('/export-order/{id}', 'OrderstatusesController@exportOrder')->name('export-order');
Route::get('/export-invoice/{id}', 'OrderstatusesController@exportInvoice')->name('export-invoice');

Route::get('/order-filter', 'OrderstatusesController@search')->name('orderstatuses');

Route::get('/product-filter', 'OrderstatusesController@search1')->name('orderstatuses');
Route::resource('first','FirstController');

Route::get('manage-discounts' , 'DiscountController@index')->name('manage-discounts');
Route::post('update-discounts' , 'DiscountController@update')->name('update-discounts');

Route::get('gift-discount/{customer}' , 'DiscountController@giftDiscount')->name('gift-discount');
Route::get('remove-discount/{customer}' , 'DiscountController@removeDiscount')->name('remove-discount');

// dropzone images
Route::post('/images-save', 'GalleriesController@saveDropzoneImage')->name('images-save') ;
Route::get('/images-delete/{id}', 'GalleriesController@deleteDropzoneImage');








Route::post('/update-category-order', 'CategoriesController@updateOrder') ;

Route::post('/update-product-order', 'ProductsController@updateOrder') ;

// Route::get('test', function(){
//     // return view('layouts.main');
//     $orderstatuses = orderstatuses::latest()->first();
    
//     $customer = regusers::where('id' ,$orderstatuses->cid )->get();

//     $message = 'Dear '. $orderstatuses->customer->full_name.', we have received order # ' . $orderstatuses->id .' and are working on it now.<br></p><p style="color: #242424;">We will email you an update when we have delivered it.<br>';

//     $subject = 'Your vQuick Order is submitted';

//     dispatch(new SendCustomerEmail($customer , $message , $subject , $orderstatuses ));

// });

Route::get('email-test' , function(){

    $order = orderstatuses::latest()->first();

    $customer = regusers::where('id' ,$order->cid )->get();

    $message = 'Dear '. $order->customer->full_name.', we have received order # ' . $order->id .' and are working on it now.<br></p><p style="color: #242424;">We will email you an update when we have delivered it.<br>';

    $subject = 'Your vQuick Order is submitted';

    dispatch(new SendCustomerEmailCheck($customer , $message , $subject , $order ));
    echo "Email is dispatched  " . Carbon::now();
} );

Route::get('start-queue' , function(){
    Artisan::call("queue:restart");
    Artisan::call("queue:work");    
});


Route::get('invoice/{id}', function($id){

    $order = orderstatuses::find( $id );
    $msg = 'message';
    // return view('pdf.invoice' , compact('order' , 'msg') );
    return view('pdf.pdf_invoice2' , compact('order' , 'msg') );
});

Route::get('payment_success', function(){
    // return view('payment_success');
});

resources/views/admins/create.blade.php
@extends('admins.layout')
@section('content')
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="pull-left">
        <h2>Add New Admin</h2>
      </div>
      <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('admins.index') }}"> Back</a>
      </div>
    </div>
  </div>
      
  @if ($errors->any())
  <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
      <ul>
        @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
  @endif

  

  <form action="{{ route('admins.store') }}" method="POST">
    @csrf
    
    <div class="row" style="width:80%;margin:auto;">   

      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Email:</strong>
          <input type="text" class="form-control" name="email" placeholder="Enter Email" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Password:</strong>
          <input type="password" class="form-control" placeholder="Enter Password" name="password" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Name:</strong>
          <input type="text" class="form-control" name="name" placeholder="Enter Name" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>    
  </form>
  @endsection

resources/views/admins/edit.blade.php
@extends('admins.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Users</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('admins.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('admins.update', $admin->id) }}" method="POST">
        @csrf
        @method('PUT')
   
        <div class="row" style="width:80%;margin:auto;">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Email:</strong>
              <input type="text" class="form-control" name="email" value="{{ $admin->email }}" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12" >
            <div class="form-group">
              <strong>Name:</strong>
              <input type="text" class="form-control" name="name" value="{{ $admin->name }}" required="required"/>
            </div>
          </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/admins/index.blade.php
@extends('admins.layout') 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('admins.create') }}"> Create New Admin</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bregusered">
        <tr>
          <th>No</th>
          <th>Email</th>
          <th>Name</th>
          <th width="280px">Action</th>
        </tr>
        @foreach ($admins as $admin)
        <tr>
          <td>{{ ++$i }}</td>
          <td>{{ $admin->email }}</td>
          <td>{{ $admin->name }}</td>
          <td>
            <form id="delete-form-{{$admin->id}}" action="{{ route('admins.destroy',$admin->id) }}" method="POST">
              {{--  <a class="btn btn-info" href="{{ route('admins.show',$admin->id) }}">Show</a>  --}}
              <a class="btn btn-primary" href="{{ route('admins.edit',$admin->id) }}">Edit</a>
              @csrf
              @method('DELETE')
              <button type="button" onclick="ask_delete({{$admin->id}})" class="btn btn-danger">Delete</button>
            </form>
          </td>
        </tr>
        @endforeach
    </table>
  
      

@endsection

resources/views/admins/layout.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>VQuick | Dashboard</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{{asset('css/app.css')}}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">


    
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    @include('/header');
    @include('/aside');
    <div class="content-wrapper">
        <section class="content-header">
            <h1 style="float:left;">
                Admins
            </h1>
        </section>
        <div style="padding:5%;">
            @yield('content')
        </div>
    </div>
    <footer class="main-footer">
        <strong>Copyright &copy; 2020 <a href="#">vQuick</a>.</strong> All rights reserved.
    </footer>
</div>
<script src="{{asset('js/app.js')}}"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<script>
    function ask_delete(id){
        
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
          }).then((result) => {
            if (result.value) {
                $('#delete-form-'+id).submit();
            }
          });   
    }

</script>
</body>
</html>

resources/views/admins/show.blade.php
@extends('admins.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show User Details</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('admins.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $admin->email }}<br>
                <strong>Full Name:</strong>
                {{ $admin->name }}
            </div>
        </div>
    </div>
@endsection