routes/web.php
<?php

// use ImageOptimizer;

use App\Area;
use App\carts;
use App\Discount;

Route::get('/', function () {
    return view('welcome');
});
Route::get('/contact', function () {
    return view('contact');
})->name('contact') ; 


Route::get('/about', function () {
    return view('about');
})->name('about') ;


  //  language change
  Route::get('change-language/{lang}' , function($lang){
    
    App::setLocale($lang);

    session()->put('locale', $lang);

    if(session('locale') == 'ar'){

        $_SESSION['language'] = 'arabic' ;
    }else{
        $_SESSION['language'] = 'english' ;

    }
    return redirect()->back();

    
} ) ->name ('change-language') ;


Route::get('email', function () {

    $orderstatus = App\orderstatuses::find(38);
    $shipping = App\shippings::first();
    // , , 'shipping' => $shipping
    return view('emails.order_status' , ['msg' => 'Hello World' , 'order' => $orderstatus  ] );
})->name('email') ;


Route::get('/product', 'ProductsController@showProducts' )->name('product') ;

Route::get('/gallery', 'GalleriesController@showGalleryImages' )->name('gallery') ;

// Route::get('/product', function () {
//     return view('product');
// });
Route::get('/userlogin', function () {


    // dd(url()->previous());

    if(isset($_SESSION['logged_in'])){
        return redirect()->back()->with('error' , 'Already Logged in');
    }
    if(strpos( url()->previous() ,  'checkout') ){
        session()->put('checkout' , 'checkout');
    }

    return view('userlogin');

})->name('userlogin') ;
Route::get('/signup', function () {

    if(isset($_SESSION['logged_in'])){
        return redirect()->back()->with('error' , 'Already Logged in');
    }

    if(strpos( url()->previous() ,  'checkout') ){
        session()->put('checkout' , 'checkout');
    }
    $areas = Area::all();
    return view('signup' , compact('areas'));
});


Route::get('reset/password','RegusersController@resetEmailPassword')->name('reset.password');
Route::post('send-reset-password-link','RegusersController@sentPasswordResetLink')->name('send-reset-password-link');

Route::post('save-new-password','RegusersController@sentNewPassword')->name('save-new-password');


Route::get('password/reset/{email}/token/{token}','RegusersController@resetPassword')->name('password.reset.token');


Route::get('edit-profile' , 'RegusersController@editProfile')->name('edit-profile');


if(!isset($_SESSION)) 
{ 
    session_start(); 
}
use App\products;
use App\regusers;
use App\shippings;
use Carbon\Carbon;
use App\contactuses;
use App\orderstatuses;
use App\Jobs\SendDiscountMail;
use App\Jobs\SendCustomerEmail;
use App\Jobs\SendCustomerEmailCheck;
use Illuminate\Support\Facades\Route;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Artisan;
use Spatie\ImageOptimizer\OptimizerChainFactory;

Route::get('/checkout', "CheckoutController@viewCart" )->name('checkout') ;
Auth::routes();

Route::get('/home', 'AbcController@index')->middleware('auth');
Route::get('/header', 'HeaderController@index')->name('header');
Route::get('/aside', 'AsideController@index')->name('aside');
Route::resource('homes','HomeController')->middleware('auth');
Route::resource('categories','CategoriesController')->middleware('auth');
Route::get('/manage-category', 'CategoriesController@approve')->name('category');
Route::resource('products','ProductsController')->middleware('auth');

Route::get('products/exports/{ids}','ProductsController@exportProducts')->name('products.exports');

Route::get('/manage-products', 'ProductsController@approve')->name('products');
Route::resource('aboutuses','AboutusesController')->middleware('auth');
Route::resource('contactuses','ContactusesController')->middleware('auth');
Route::resource('orders','OrdersController')->middleware('auth');
Route::resource('homepages','HomepagesController')->middleware('auth');
Route::resource('galleries','GalleriesController')->middleware('auth');
Route::resource('shippings','ShippingsController')->middleware('auth');
Route::resource('areas','AreaController')->middleware('auth');
Route::get('areas/delete/{id}','AreaController@destroy')->name('areas.delete') ->middleware('auth');

Route::resource('regusers','RegusersController');

Route::post('guest-signup' ,'RegusersController@guestSignup' )->name('guest-signup') ;
Route::get('guest-signup' ,'RegusersController@guestSignup' )->name('guest-signup') ;

Route::get('reguser/{user}/orders','RegusersController@viewOrders')->name('reguser-orders');


Route::get('filter-users' , 'RegusersController@filter' )->name('filter-users') ;
Route::get('/export-customers/{ids}', 'RegusersController@exportCustomers')->name('export-customers');

Route::resource('carts','CartsController');
Route::resource('productsections','ProductsectionsController')->middleware('auth');
Route::get('/user-login', 'RegusersController@login')->name('orders');
Route::get('/user-logout', 'RegusersController@logout')->name('orders');
Route::get('/contact-form', 'ContactFormController@store')->name('orders');

Route::get('/carts', 'CartsController@store')->name('carts');
Route::get('/update-cart-quantity', 'CartsController@updateCartQuantity')->name('update-cart-quantity');

Route::get('/update-cart-quantity-ajax/{cart_id}/{quantity}', 'CartsController@updateCartQuantityAjax')->name('update-cart-quantity-ajax');

Route::post('register-guest', 'RegusersController@guestSignupStore')->name('register-guest') ;

Route::post('/order-cart', 'OrderstatusesController@store')->name('orderstatuses');
Route::get('/order-cart', 'OrderstatusesController@store')->name('orderstatuses');

Route::get('/sadad-payment', 'OrderstatusesController@sadadPayment')->name('sadad-payment');

Route::get('/sadad-payment-success', 'OrderstatusesController@sadadPaymentSuccess')->name('sadad-payment-success');

Route::post('/sadad-payment-success', 'OrderstatusesController@sadadPaymentSuccess')->name('sadad-payment-success');


Route::get('paymentsuccess', 'OrderstatusesController@payment_success');
Route::get('paymenterror', 'OrderstatusesController@payment_error');

Route::get('/delete-cart', 'CartsController@delete')->name('carts');
Route::resource('admins','AdminsController')->middleware('auth');

Route::get('/contact-form','ContactFormController@create');
Route::post('/contact-form','ContactFormController@store');
Route::post('/user-logout','RegusersController@logout');
Route::post('/user-login', 'RegusersController@login');
// Route::get('/product-category', 'ProductsController@show1')->name('products');
Route::get('/product-category', 'ProductsController@showCategoryProducts')->name('products');

Route::get('/gallery-images', 'GalleriesController@showGallery')->name('gallery-images');

Route::get('/order-history', 'OrdersController@showHistory')->name('order-history');
Route::get('/order-history/{order}/details', 'OrdersController@showOrderDetails')->name('order-history.details');

Route::resource('orderstatuses','OrderstatusesController')->middleware('auth');

Route::get('/export-orders/{ids}', 'OrderstatusesController@exportOrders')->name('export-orders');

Route::get('/export-orders-products/{ids}', 'OrderstatusesController@exportOrdersProducts')->name('export-orders-products');

Route::get('/export-order/{id}', 'OrderstatusesController@exportOrder')->name('export-order');
Route::get('/export-invoice/{id}', 'OrderstatusesController@exportInvoice')->name('export-invoice');

Route::get('/order-filter', 'OrderstatusesController@search')->name('orderstatuses');

Route::get('/product-filter', 'OrderstatusesController@search1')->name('orderstatuses');
Route::resource('first','FirstController');

Route::get('manage-discounts' , 'DiscountController@index')->name('manage-discounts');
Route::post('update-discounts' , 'DiscountController@update')->name('update-discounts');

Route::get('gift-discount/{customer}' , 'DiscountController@giftDiscount')->name('gift-discount');
Route::get('remove-discount/{customer}' , 'DiscountController@removeDiscount')->name('remove-discount');

// dropzone images
Route::post('/images-save', 'GalleriesController@saveDropzoneImage')->name('images-save') ;
Route::get('/images-delete/{id}', 'GalleriesController@deleteDropzoneImage');








Route::post('/update-category-order', 'CategoriesController@updateOrder') ;

Route::post('/update-product-order', 'ProductsController@updateOrder') ;

// Route::get('test', function(){
//     // return view('layouts.main');
//     $orderstatuses = orderstatuses::latest()->first();
    
//     $customer = regusers::where('id' ,$orderstatuses->cid )->get();

//     $message = 'Dear '. $orderstatuses->customer->full_name.', we have received order # ' . $orderstatuses->id .' and are working on it now.<br></p><p style="color: #242424;">We will email you an update when we have delivered it.<br>';

//     $subject = 'Your vQuick Order is submitted';

//     dispatch(new SendCustomerEmail($customer , $message , $subject , $orderstatuses ));

// });

Route::get('email-test' , function(){

    $order = orderstatuses::latest()->first();

    $customer = regusers::where('id' ,$order->cid )->get();

    $message = 'Dear '. $order->customer->full_name.', we have received order # ' . $order->id .' and are working on it now.<br></p><p style="color: #242424;">We will email you an update when we have delivered it.<br>';

    $subject = 'Your vQuick Order is submitted';

    dispatch(new SendCustomerEmailCheck($customer , $message , $subject , $order ));
    echo "Email is dispatched  " . Carbon::now();
} );

Route::get('start-queue' , function(){
    Artisan::call("queue:restart");
    Artisan::call("queue:work");    
});


Route::get('invoice/{id}', function($id){

    $order = orderstatuses::find( $id );
    $msg = 'message';
    // return view('pdf.invoice' , compact('order' , 'msg') );
    return view('pdf.pdf_invoice2' , compact('order' , 'msg') );
});

Route::get('payment_success', function(){
    // return view('payment_success');
});

app/Area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
    protected $guarded = [];

    protected $casts = [
        'charges' => 'integer',
    ];

    public function getProperAreaAttribute($value){

        if(session('locale') == 'ar'){
            return $this->ar_area;
        }else{
            return $this->area;
        }
    }

}

app/regusers.php
<?php

namespace App;

use Carbon\Carbon;
use App\Jobs\SendDiscountMail;
use Illuminate\Database\Eloquent\Model;

class regusers extends Model
{
    // protected $fillable = [
    //     'email','password','full_name','phone','address','zone','street','building' , 'is_guest'
    // ];

    protected $guarded = [];


    protected static function boot()
    {
        
        static::retrieved(function ($customer) {

            // dd(Carbon::parse($customer->discount_end_date) , Carbon::now() , Carbon::parse($customer->discount_end_date) <= Carbon::now());
            if($customer->has_discount == 1 && Carbon::parse($customer->discount_end_date) <= Carbon::now() ){
                $customer->has_discount = 0;
                $customer->discount_end_date = null;
                $customer->save();
            }

            if($customer->is_guest == 0){

                $discount = Discount::first();

                if(isset($discount) && $customer->new_orders->count() >= $discount->orders ){
                    
                    // dd('discount given' , $customer->new_orders );
                    // $customer->orders()->delete();

                    $customer->has_discount = 1;
                    $customer->discount_end_date = Carbon::now()->addDays(30)->toDateString();
                    $customer->save();
                    foreach($customer->new_orders as $order){
                        $order->counted_for_discount = 1;
                        $order->save();
                    }

                    dispatch(new SendDiscountMail($customer ));

                }
            }


            // if($customer->is_guest == 1 && $customer->has_discount == 1){
            //     $customer->has_discount = 0;
            //     $customer->discount_end_date = null;
            //     $customer->save();
            // }
            });
        parent::boot();
    }


    public function orders(){
        return $this->hasMany(orderstatuses::class , 'cid');
    }

    public function area(){
        return $this->belongsTo(Area::class);
    }

    public function new_orders(){
        
        // return $this->hasMany(orderstatuses::class , 'cid')->whereRaw('payment_method == sadad' AND 'payment_status == paid')->orWhere('payment_method' , 'cash on delivery')->where('counted_for_discount' , 0);
        return $this->hasMany(orderstatuses::class , 'cid')->where([
                ['payment_method' , 'sadad'] ,
                ['payment_status', 'paid'] 
            ])->orWhere([
                ['payment_method' , 'cash on delivery'] , 
                ['payment_status' , 'paid'] , 
                ['status', 'delivered']
            ])->where('cid' , $this->id)
            ->where('counted_for_discount' , 0);

        
        // return $this->hasMany(orderstatuses::class , 'cid')->where([['payment_method' , 'sadad'] ,['payment_status', 'paid'] ])->orWhere([['payment_method' , 'cash on delivery'] , ['payment_status' , 'paid'] , ['status', 'delivered']] )->where('counted_for_discount' , 0);
       
    }

}

resources/views/regusers/create.blade.php
@extends('regusers.layout')
@section('content')
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="pull-left">
        <h2>Add New Customer</h2>
      </div>
      <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('regusers.index') }}"> Back</a>
      </div>
    </div>
  </div>
      
  @if ($errors->any())
  <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
      <ul>
        @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
  @endif

  

  <form action="{{ route('regusers.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    
    <div class="row" style="width:80%;margin:auto;">   

      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Email:</strong>
          <input type="text" class="form-control" name="email" placeholder="Enter Email" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Password:</strong>
          <input type="password" class="form-control" placeholder="Enter Password" name="password" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Name:</strong>
          <input type="text" class="form-control" name="full_name" placeholder="Enter Name" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Mobile:</strong>
          <input type="text" class="form-control" name="phone" placeholder="Enter Mobile" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Area:</strong>
          <select class="form-control" required name="area" >
            <option value="">{{__('Select Area')}}</option>
            @foreach($areas as $area)
            <option value="{{$area->id}}"> {{$area->proper_area}} </option>
            @endforeach
          </select>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Address:</strong>
          <input type="text" class="form-control" name="address" placeholder="Enter Address" required="required"/>
        </div>
      </div>
      {{--  <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Zone:</strong>
          <input type="text" class="form-control" placeholder="Enter Zone No" name="zone" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Street:</strong>
          <input type="text" class="form-control" placeholder="Enter Street No" name="street" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Bilding:</strong>
          <input type="text" class="form-control" name="building" placeholder="Enter Building No" required="required"/>
        </div>
      </div>  --}}
      <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>    
  </form>
  @endsection

resources/views/regusers/edit.blade.php
@extends('regusers.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Customer</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('regusers.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('regusers.update', $reguser->id) }}" method="POST">
        @csrf
        @method('PUT')
   
        <div class="row" style="width:80%;margin:auto;">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Email:</strong>
              <input type="text" class="form-control" name="email" value="{{ $reguser->email }}" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Password:</strong>
              <input type="password" class="form-control" value="{{ $reguser->password }}" name="password" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12" >
            <div class="form-group">
              <strong>Name:</strong>
              <input type="text" class="form-control" name="full_name" value="{{ $reguser->full_name }}" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12" >
            <div class="form-group">
              <strong>Mobile:</strong>
              <input type="text" class="form-control" name="phone" value="{{ $reguser->phone }}" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12" >
            <div class="form-group">
              <strong>Area:</strong>
              <select class="form-control" required name="area" >
                <option value="">{{__('Select Area')}}</option>
                @foreach($areas as $area)
                <option value="{{$area->id}}" @if($reguser->area && $reguser->area_id == $area->id) selected @endif > {{$area->proper_area}} </option>
                @endforeach
              </select>
            </div>
          </div>
    
          <div class="col-xs-12 col-sm-12 col-md-12" >
            <div class="form-group">
              <strong>Address:</strong>
              <input type="text" class="form-control" name="address" value="{{ $reguser->address }}" required="required"/>
            </div>
          </div>
          {{--  <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Zone:</strong>
              <input type="text" class="form-control" value="{{ $reguser->zone }}" name="zone" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Street:</strong>
              <input type="text" class="form-control" value="{{ $reguser->street }}" name="street" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Bilding:</strong>
              <input type="text" class="form-control" name="building" value="{{ $reguser->building }}" required="required"/>
            </div>
          </div>  --}}
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/regusers/index.blade.php
@extends('regusers.layout') 

@section('content')

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<form action="{{route('filter-users')}}" method="GET">

  <div class="col-12" style="display:grid;grid-template-columns:25% 25% 25% 20%;grid-column-gap:3%;">
      <div class="form-group mt-2">
        <input type="text" class="form-control" name="name" placeholder="Name"  @if(isset($filters) && isset($filters['name']) ) value="{{$filters['name']}}" @endif />
      </div>
      <div class="form-group mt-2">
        <input type="text" name="phone" class="form-control" placeholder="Phone" @if(isset($filters) && isset($filters['phone']) ) value="{{$filters['phone']}}" @endif  />
      </div>
      
      <div class="form-group mt-2">
        <input type="email" name="email" class="form-control" placeholder="Email" @if(isset($filters) && isset($filters['email']) ) value="{{$filters['email']}}" @endif  />
      </div>
         <div class="form-group mt-2">
           <select class="form-control" name="discount"  >

              <option value=""> Select Discount Status </option>
              <option value="1"@if(isset($filters) && isset($filters['discount']) && $filters['discount'] == 1) selected @endif > Loyality User </option>
              <option value="0"@if(isset($filters) && isset($filters['discount']) && $filters['discount'] == 0) selected @endif > Normal Users </option>
           </select>
      </div>
      
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Search</button>
        <a class="btn btn-danger" href="{{route('regusers.index')}}">X Clear</a>
      </div>
      <div class="form-group">
      </div>
    </div>
  </form>

  @php
    if(isset($filtered_regusers)){
      $regusers = $filtered_regusers;
    }
@endphp

<div class="row">
        <div class="col-lg-12 margin-tb mb-3">
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('export-customers' , json_encode ( $regusers->pluck('id')->toArray()) ) }}"> Export</a>
                <a class="btn btn-success ml-2" href="{{ route('regusers.create') }}"> Create New Customer</a>
            </div>
        </div>
      
       
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bregusered">
        <tr>
          <th>No</th>
          <th>Name</th>
          <th>Email</th>
          <th>Mobile Number</th>
          <th>Address</th>
          <th>Discount End</th>
          <!--<th>Zone</th>-->
          <!--<th>Street</th>-->
          <!--<th>Building</th>-->
          <th width="280px">Action</th>
        </tr>
        @foreach ($regusers as $k => $reguser)
        <tr>
          <td>{{ $k+1 }}</td>
          <td>{{ $reguser->full_name }}
            @if(isset($reguser) && $reguser->has_discount == 1)
            <img src="{{asset('files/important.png')}}" style="width:20px; height:auto" >
            @endif

          </td>
          <td> {{ $reguser->email }} </td>
          <td>{{ $reguser->phone }}</td>
          <td>{{ $reguser->address }}</td>
          <td>{{ $reguser->discount_end_date }}</td>
          <!--<td>{{ $reguser->zone }}</td>-->
          <!--<td>{{ $reguser->street }}</td>-->
          <!--<td>{{ $reguser->building }}</td>-->
          <td>
            <a href="javascript:;"onclick="ask_delete({{$reguser->id}})" class="text-danger "> <i class="fa fa-trash fa-lg"></i> </a>

            <a href="{{ route('regusers.edit',$reguser->id) }}" class=""> <i class="fa fa-edit fa-lg"></i> </a>

            <form style="display: inline" id="delete-form-{{$reguser->id}}" action="{{ route('regusers.destroy',$reguser->id) }}" method="POST">
              <!--<a class="btn btn-info btn-sm" href="{{ route('regusers.show',$reguser->id) }}">Show</a>-->
              {{-- <a class="btn btn-primary" href="{{ route('regusers.edit',$reguser->id) }}">Edit</a> --}}
              @csrf
              @method('DELETE')
              {{--  <button type="submit" class="btn btn-danger">Delete</button>  --}}

            </form>
            <a href="{{route('reguser-orders' , $reguser->id )}}"  class="btn btn-primary btn-sm">Orders </a>
            
            @if($reguser->is_guest == 0)
            @if((isset($discount) && $discount->orders))
            @if($reguser->has_discount == 1)
            <a href="{{route('remove-discount' , $reguser->id )}}"  class="btn btn-danger btn-sm">Remove Discount </a>
            @else
            <a href="{{route('gift-discount' , $reguser->id )}}"  class="btn btn-success btn-sm">Gift Discount </a>
            @endif
            @endif
            @endif


          </td>
        </tr>
        @endforeach
    </table>

</div>



    @if(
      $regusers instanceof \Illuminate\Pagination\Paginator ||
      $regusers instanceof Illuminate\Pagination\LengthAwarePaginator
    )
  
      {{$regusers->links() ?? ''}}
  @endif
  

 
      
@endsection

resources/views/regusers/show.blade.php
@extends('regusers.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Customer Details</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('regusers.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $reguser->email }}<br>
                <strong>Full Name:</strong>
                {{ $reguser->full_name }}<br>
                <strong>Mobile Number:</strong>
                {{ $reguser->phone }}<br>
                <strong>Address:</strong>
                {{ $reguser->address }}<br>
                <strong>Zone No.:</strong>
                {{ $reguser->zone }}<br>
                <strong>Street No.:</strong>
                {{ $reguser->street }}<br>
                <strong>Building No.:</strong>
                {{ $reguser->building }}
            </div>
        </div>
    </div>
@endsection

resources/views/regusers/user_orders.blade.php
@extends('orderstatuses.layout') 
@section('content')


<style>
  .badge-danger{
    background-color: red;
    color:white;
  }
  .badge-success{

  }
  .badge-primary{

  }
  .badge-warning{

  }
</style>


    <?php use App\regusers;?>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
  


 <table class="table table-bordered">
        <tr>
          <th>Order Number</th>
          <th>Customer Name</th>
          <th>Payment Status</th>
          <th>Payment Method</th>
          <th>Transaction Number</th>
          <th>Status</th>
          <th>Mobile Number</th>
          <th>Address</th>
          <th>Shipping Area</th>
          <th>Shipping Charges</th>
          <th>Total Price</th>
          <th>Discounted Price</th>
          <th>Date Time</th>
          <th width="280px">Action</th>
        </tr>
        
        @foreach ($customer->orders->sortByDesc('id')  as $orderstatus)
        
        @if(!($orderstatus->payment_method == 'sadad' && $orderstatus->payment_status == 'pending'))

       <tr>
          <td>{{ $orderstatus->id }}</td>

          <td>{{ $orderstatus->customer->full_name ?? '' }}</td>

          <td>{{ $orderstatus->payment_status }}</td>

          <td>{{ $orderstatus->payment_method }}</td>
          <td>{{ $orderstatus->transaction_number }}</td>

          <td>
            @if($orderstatus->status == 'pending')
            <span class="label label-danger">Pending</span>
            
            @elseif($orderstatus->status == 'confirmed')

            <span class="label label-primary">Confirmed</span>
            
            @elseif($orderstatus->status == 'out for delivery')
            
            <span class="label label-warning">Out For Delivery</span>
            
            @elseif($orderstatus->status == 'delivered')
            
            <span class="label label-success">Delivered</span>

            @elseif($orderstatus->status == 'cancelled')
            
            <span class="label label-danger">Cancelled</span>
            
            @endif
            
            <td>{{ $orderstatus->customer->phone ?? '' }}</td>
         
            <td>{{ $orderstatus->customer->address ?? '' }}</td>

            <td> {{ $orderstatus->area ? $orderstatus->area->area : "" }}</td>
            
            <td> @if($orderstatus->shipping_charges) {{ $orderstatus->shipping_charges }} QTR @endif</td>
            
            
            <td>{{ $orderstatus->carts->count() > 0 ? array_sum($orderstatus->carts->pluck('original_price')->toArray()) +  $orderstatus->charges : '' }} QTR </td> 
            
            
            <td>{{ $orderstatus->total_price }} QTR</td>
  
  
            <td>{{ $orderstatus->created_at }}</td>


          <td>
            <form id="delete-form-{{$orderstatus->id}}" action="{{ route('orderstatuses.destroy',$orderstatus->id) }}" method="POST">
              <a class="btn btn-info" href="{{ route('orderstatuses.show',$orderstatus->id) }}">View</a>
              <a class="btn btn-primary" href="{{ route('orderstatuses.edit',$orderstatus->id) }}">Edit</a>
              @csrf
              @method('DELETE')
              {{--  <button type="submit" class="btn btn-danger">Delete</button>  --}}
              <button type="button" onclick="ask_delete({{$orderstatus->id}})" class="btn btn-danger">Delete</button>

            </form>
          </td>
        </tr>
        @endif
        @endforeach
    </table>
  

@endsection