routes/web.php
<?php

// use ImageOptimizer;

use App\Area;
use App\carts;
use App\Discount;

Route::get('/', function () {
    return view('welcome');
});
Route::get('/contact', function () {
    return view('contact');
})->name('contact') ; 


Route::get('/about', function () {
    return view('about');
})->name('about') ;


  //  language change
  Route::get('change-language/{lang}' , function($lang){
    
    App::setLocale($lang);

    session()->put('locale', $lang);

    if(session('locale') == 'ar'){

        $_SESSION['language'] = 'arabic' ;
    }else{
        $_SESSION['language'] = 'english' ;

    }
    return redirect()->back();

    
} ) ->name ('change-language') ;


Route::get('email', function () {

    $orderstatus = App\orderstatuses::find(38);
    $shipping = App\shippings::first();
    // , , 'shipping' => $shipping
    return view('emails.order_status' , ['msg' => 'Hello World' , 'order' => $orderstatus  ] );
})->name('email') ;


Route::get('/product', 'ProductsController@showProducts' )->name('product') ;

Route::get('/gallery', 'GalleriesController@showGalleryImages' )->name('gallery') ;

// Route::get('/product', function () {
//     return view('product');
// });
Route::get('/userlogin', function () {


    // dd(url()->previous());

    if(isset($_SESSION['logged_in'])){
        return redirect()->back()->with('error' , 'Already Logged in');
    }
    if(strpos( url()->previous() ,  'checkout') ){
        session()->put('checkout' , 'checkout');
    }

    return view('userlogin');

})->name('userlogin') ;
Route::get('/signup', function () {

    if(isset($_SESSION['logged_in'])){
        return redirect()->back()->with('error' , 'Already Logged in');
    }

    if(strpos( url()->previous() ,  'checkout') ){
        session()->put('checkout' , 'checkout');
    }
    $areas = Area::all();
    return view('signup' , compact('areas'));
});


Route::get('reset/password','RegusersController@resetEmailPassword')->name('reset.password');
Route::post('send-reset-password-link','RegusersController@sentPasswordResetLink')->name('send-reset-password-link');

Route::post('save-new-password','RegusersController@sentNewPassword')->name('save-new-password');


Route::get('password/reset/{email}/token/{token}','RegusersController@resetPassword')->name('password.reset.token');


Route::get('edit-profile' , 'RegusersController@editProfile')->name('edit-profile');


if(!isset($_SESSION)) 
{ 
    session_start(); 
}
use App\products;
use App\regusers;
use App\shippings;
use Carbon\Carbon;
use App\contactuses;
use App\orderstatuses;
use App\Jobs\SendDiscountMail;
use App\Jobs\SendCustomerEmail;
use App\Jobs\SendCustomerEmailCheck;
use Illuminate\Support\Facades\Route;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Artisan;
use Spatie\ImageOptimizer\OptimizerChainFactory;

Route::get('/checkout', "CheckoutController@viewCart" )->name('checkout') ;
Auth::routes();

Route::get('/home', 'AbcController@index')->middleware('auth');
Route::get('/header', 'HeaderController@index')->name('header');
Route::get('/aside', 'AsideController@index')->name('aside');
Route::resource('homes','HomeController')->middleware('auth');
Route::resource('categories','CategoriesController')->middleware('auth');
Route::get('/manage-category', 'CategoriesController@approve')->name('category');
Route::resource('products','ProductsController')->middleware('auth');

Route::get('products/exports/{ids}','ProductsController@exportProducts')->name('products.exports');

Route::get('/manage-products', 'ProductsController@approve')->name('products');
Route::resource('aboutuses','AboutusesController')->middleware('auth');
Route::resource('contactuses','ContactusesController')->middleware('auth');
Route::resource('orders','OrdersController')->middleware('auth');
Route::resource('homepages','HomepagesController')->middleware('auth');
Route::resource('galleries','GalleriesController')->middleware('auth');
Route::resource('shippings','ShippingsController')->middleware('auth');
Route::resource('areas','AreaController')->middleware('auth');
Route::get('areas/delete/{id}','AreaController@destroy')->name('areas.delete') ->middleware('auth');

Route::resource('regusers','RegusersController');

Route::post('guest-signup' ,'RegusersController@guestSignup' )->name('guest-signup') ;
Route::get('guest-signup' ,'RegusersController@guestSignup' )->name('guest-signup') ;

Route::get('reguser/{user}/orders','RegusersController@viewOrders')->name('reguser-orders');


Route::get('filter-users' , 'RegusersController@filter' )->name('filter-users') ;
Route::get('/export-customers/{ids}', 'RegusersController@exportCustomers')->name('export-customers');

Route::resource('carts','CartsController');
Route::resource('productsections','ProductsectionsController')->middleware('auth');
Route::get('/user-login', 'RegusersController@login')->name('orders');
Route::get('/user-logout', 'RegusersController@logout')->name('orders');
Route::get('/contact-form', 'ContactFormController@store')->name('orders');

Route::get('/carts', 'CartsController@store')->name('carts');
Route::get('/update-cart-quantity', 'CartsController@updateCartQuantity')->name('update-cart-quantity');

Route::get('/update-cart-quantity-ajax/{cart_id}/{quantity}', 'CartsController@updateCartQuantityAjax')->name('update-cart-quantity-ajax');

Route::post('register-guest', 'RegusersController@guestSignupStore')->name('register-guest') ;

Route::post('/order-cart', 'OrderstatusesController@store')->name('orderstatuses');
Route::get('/order-cart', 'OrderstatusesController@store')->name('orderstatuses');

Route::get('/sadad-payment', 'OrderstatusesController@sadadPayment')->name('sadad-payment');

Route::get('/sadad-payment-success', 'OrderstatusesController@sadadPaymentSuccess')->name('sadad-payment-success');

Route::post('/sadad-payment-success', 'OrderstatusesController@sadadPaymentSuccess')->name('sadad-payment-success');


Route::get('paymentsuccess', 'OrderstatusesController@payment_success');
Route::get('paymenterror', 'OrderstatusesController@payment_error');

Route::get('/delete-cart', 'CartsController@delete')->name('carts');
Route::resource('admins','AdminsController')->middleware('auth');

Route::get('/contact-form','ContactFormController@create');
Route::post('/contact-form','ContactFormController@store');
Route::post('/user-logout','RegusersController@logout');
Route::post('/user-login', 'RegusersController@login');
// Route::get('/product-category', 'ProductsController@show1')->name('products');
Route::get('/product-category', 'ProductsController@showCategoryProducts')->name('products');

Route::get('/gallery-images', 'GalleriesController@showGallery')->name('gallery-images');

Route::get('/order-history', 'OrdersController@showHistory')->name('order-history');
Route::get('/order-history/{order}/details', 'OrdersController@showOrderDetails')->name('order-history.details');

Route::resource('orderstatuses','OrderstatusesController')->middleware('auth');

Route::get('/export-orders/{ids}', 'OrderstatusesController@exportOrders')->name('export-orders');

Route::get('/export-orders-products/{ids}', 'OrderstatusesController@exportOrdersProducts')->name('export-orders-products');

Route::get('/export-order/{id}', 'OrderstatusesController@exportOrder')->name('export-order');
Route::get('/export-invoice/{id}', 'OrderstatusesController@exportInvoice')->name('export-invoice');

Route::get('/order-filter', 'OrderstatusesController@search')->name('orderstatuses');

Route::get('/product-filter', 'OrderstatusesController@search1')->name('orderstatuses');
Route::resource('first','FirstController');

Route::get('manage-discounts' , 'DiscountController@index')->name('manage-discounts');
Route::post('update-discounts' , 'DiscountController@update')->name('update-discounts');

Route::get('gift-discount/{customer}' , 'DiscountController@giftDiscount')->name('gift-discount');
Route::get('remove-discount/{customer}' , 'DiscountController@removeDiscount')->name('remove-discount');

// dropzone images
Route::post('/images-save', 'GalleriesController@saveDropzoneImage')->name('images-save') ;
Route::get('/images-delete/{id}', 'GalleriesController@deleteDropzoneImage');








Route::post('/update-category-order', 'CategoriesController@updateOrder') ;

Route::post('/update-product-order', 'ProductsController@updateOrder') ;

// Route::get('test', function(){
//     // return view('layouts.main');
//     $orderstatuses = orderstatuses::latest()->first();
    
//     $customer = regusers::where('id' ,$orderstatuses->cid )->get();

//     $message = 'Dear '. $orderstatuses->customer->full_name.', we have received order # ' . $orderstatuses->id .' and are working on it now.<br></p><p style="color: #242424;">We will email you an update when we have delivered it.<br>';

//     $subject = 'Your vQuick Order is submitted';

//     dispatch(new SendCustomerEmail($customer , $message , $subject , $orderstatuses ));

// });

Route::get('email-test' , function(){

    $order = orderstatuses::latest()->first();

    $customer = regusers::where('id' ,$order->cid )->get();

    $message = 'Dear '. $order->customer->full_name.', we have received order # ' . $order->id .' and are working on it now.<br></p><p style="color: #242424;">We will email you an update when we have delivered it.<br>';

    $subject = 'Your vQuick Order is submitted';

    dispatch(new SendCustomerEmailCheck($customer , $message , $subject , $order ));
    echo "Email is dispatched  " . Carbon::now();
} );

Route::get('start-queue' , function(){
    Artisan::call("queue:restart");
    Artisan::call("queue:work");    
});


Route::get('invoice/{id}', function($id){

    $order = orderstatuses::find( $id );
    $msg = 'message';
    // return view('pdf.invoice' , compact('order' , 'msg') );
    return view('pdf.pdf_invoice2' , compact('order' , 'msg') );
});

Route::get('payment_success', function(){
    // return view('payment_success');
});

app/products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class products extends Model
{
    protected $fillable = [
        'image', 'name','arabic_name', 'description' , 'description_ar','price','stock_available','category','is_approved' 
    ];



    public function getProperNameAttribute($value){

        if(session('locale') == 'ar'){
            return $this->arabic_name;
        }else{
            return $this->name;
        }
    }

    public function getProperDescriptionAttribute($value){

        if(session('locale') == 'ar'){
            return $this->description_ar;
        }else{
            return $this->description;
        }
    }


}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('products');
    }
}

resources/views/products/create.blade.php
@extends('products.layout')
@section('content')


<style>
  input[type="file"] {
      display: block;
    }
    .imageThumb {
      max-height: 75px;
      border: 2px solid;
      padding: 1px;
      cursor: pointer;
    }
    .pip {
      display: inline-block;
      margin: 10px 10px 0 0;
    }
    .remove {
      display: block;
      background: #444;
      border: 1px solid black;
      color: white;
      text-align: center;
      cursor: pointer;
    }
    .remove:hover {
      background: white;
      color: black;
    } 
    
    .image-preview-tag{
      width: 130px;
      height: 130px;
      border-radius: 4%;
  
    }
</style>


  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="pull-left">
        <h2>Add New Products</h2>
      </div>
      <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
      </div>
    </div>
  </div>
      
  @if ($errors->any())
  <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
      <ul>
        @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
  @endif

  

  <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    
    <div class="row" style="width:80%;margin:auto;">   

      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Name:</strong>
          <input type="text" class="form-control" placeholder="Enter Product Name" name="name" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>ArabicName:</strong>
          <input type="text" class="form-control" placeholder="Enter Product Name in Arabic" name="arabic_name" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>English Description:</strong>
          <textarea class="form-control" name="description" placeholder="Enter English Description" ></textarea>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Arabic Description:</strong>
          <textarea  class="form-control" name="description_ar" placeholder="Enter Arabic Description" ></textarea>
        </div>
      </div>
      {{--  <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Image:</strong>
          <input type="file" name="image" style="width:100%;" class="btn btn-success" required="required">
        </div>
      </div>  --}}
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Price:</strong>
          <input type="text" class="form-control" name="price" placeholder="Enter Price" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Stock Available:</strong>
          <input type="text" class="form-control" name="stock_available" placeholder="Enter Stock Available" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Category:</strong>
          <select class="form-control" name="category">
            <option selected disabled>Select Category</option>
            <?php use App\categories;
              $categories = categories::all(); ?>
              @foreach ($categories as $category)
                <option value="{{ $category->name}}">{{ $category->name}}</option>
              @endforeach
          </select>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Enable / Disable:</strong>
          <select class="form-control" name="is_approved">
            <option value="1">Enable</option>
            <option value="0">Disable</option>
          </select>
        </div>
      </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
          <label for="inputEmail1" class="row col-form-label ">Image Gallery:</label>
          <h2><button style="font-size: 20px" class="btn btn-success" type="button" onclick="open_images()" > <i class="fa fa-image"></i> </button></h2>
      </div>

          <div class="col-xs-12 col-sm-12 col-md-12" >
              <input type="file" name="images[]" style="display: none" multiple id="gallery-photo-add">
              <div class="gallery" id="image-preview" >
              </div>
        </div>


      <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>    
  </form>






  
  @endsection

resources/views/products/edit.blade.php
@extends('products.layout')
   
@section('content')


<style>
  .image-container{
      display: inline;
      position: relative;
  }
  .image-container .btn{
      position: absolute ;
      top: -70px;
      right: 0;
      border-radius: 50%;
      background-color: white;
      color: black;
      padding: 4px 10px !important
  }
  .video-container {
      position: relative;
      display: inline;

  }
   .video-container .btn{
      position: absolute ;
      top: -150;
      right: 0;
      border-radius: 50%;
      background-color: #c8c8c8;

  }
  
  .image-container .btn:hover{
      background-color: #c8c8c8;
      color: #fff;

  }
  
  .video-container .btn:hover{
      background-color: #c8c8c8;
      color: #fff;

  }

  .image-preview-tag{
    width: 130px;
    height: 130px;
    border-radius: 4%;

  }
</style>



    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Products</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('products.update', $product->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
   
         <div class="row" style="width:80%;margin:auto;">
         <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Name:</strong>
          {{--  <select class="form-control" name="name">
          <?php use App\products;
              $products = products::all(); ?>
            <option selected value="{{ $product->name }}">{{ $product->name }}</option>
              @foreach ($products as $product1)
                <option value="{{ $product1->name}}">{{ $product1->name}}</option>
              @endforeach
          </select>  --}}
          <input type="text" class="form-control" value="{{ $product->name }}" name="name" placeholder="Name" required="required"/>

        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Arabic Name:</strong>
          <input type="text" class="form-control" value="{{ $product->arabic_name }}" name="arabic_name" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>English Description:</strong>
          <textarea class="form-control" name="description" placeholder="Enter Category English" >{{ $product->description }}</textarea>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Arabic Description:</strong>
          <textarea  class="form-control" name="description_ar" placeholder="Enter Category Arabic" >{{ $product->description_ar }}</textarea>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Price:</strong>
          <input type="text" class="form-control" name="price" value="{{ $product->price }}" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Stock Available:</strong>
          <input type="text" class="form-control" name="stock_available" value="{{ $product->stock_available }}" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Category:</strong>
          <select class="form-control" name="category">
          <?php use App\categories;
              $categories = categories::all(); ?>
            <option selected value="{{ $product->category }}">{{ $product->category }}</option>
              @foreach ($categories as $category)
                <option value="{{ $category->name}}">{{ $category->name}}</option>
              @endforeach
          </select>
        </div>
      </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Activate/Deactivate:</strong>
                    <select class="form-control" name="is_approved">
                    <?php
                    $a=0;$a1=0;$b=0;$b1=0;
                    if($product->is_approved == '1') {
                      $a="Enabled";
                      $a1='1';
                      $b="Diable";
                      $b1='0';
                    } else {
                      $a="Disabled";
                      $a1='0';
                      $b="Enable";
                      $b1='1';
                    }?>
                        <option selected value="<?= $a1 ?>"><?= $a ?></option>
                        <option value="<?= $b1 ?>"><?= $b ?></option>
                    </select>
                </div>
            </div>

            {{--  <div class="col-xs-12 col-sm-12 col-md-12" >
              <div class="form-group">
                <strong>Image:</strong>
                <input type="file" name="image" style="width:100%;" class="btn btn-success" >
              </div>
            </div>  --}}


      
          
          <div id="deleted_images">
          </div>

  

          <div class="col-xs-12 col-sm-12 col-md-12">
            <label for="inputEmail1" class="row col-form-label ">Image Gallery:</label>
            <h2><button style="font-size: 20px" class="btn btn-success" type="button" onclick="open_images()" > <i class="fa fa-image"></i> </button></h2>
        </div>
  
            <div class="col-xs-12 col-sm-12 col-md-12" >
                <input type="file" name="images[]" style="display: none" multiple id="gallery-photo-add">
                <div class="gallery" id="image-preview" >
                  @if( $product->images && is_array(json_decode($product->images)))
                  @foreach(json_decode($product->images) as $k => $image )
                  <div class="image-container" id="image-{{$k}}" >
                  <img src="{{asset('files/'.$image)}} "  class="m-2 image-preview-tag" > 
                  <button type="button" class="btn" onclick="remove_image({{$k}})" >X</button>
                  </div>
                  @endforeach
                  @endif
                </div>
          </div>

            
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/products/index.blade.php
@extends('products.layout') 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('products.exports' , json_encode($products->pluck('id')->toArray() ) ) }}"> Export</a>
                <a class="btn btn-success" href="{{ route('products.create') }}"> Create New Products</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered">
        <tr>
          <th>No</th>
          <th>Order</th>
          <th>Name</th>
          <th>Description</th>
          <th>Image</th>
          <th>Price</th>
          <th>Status</th>
          <th>Stock Available</th>
          <th>Category</th>
          <th width="280px">Action</th>
        </tr>

        <tbody id="current-files" >
        @foreach ($products as $k => $product)
        <tr class="draggable-rows" id="{{$product->id}}" name="{{$k}}" >
          <td>{{ $k + 1 }}</td>
          <td class="index-td">{{ $product->product_order + 1 }}</td>
          <td>{{ $product->name }}</td>
          <td>{{ $product->description }}</td>
          <td><img style="width:100px;height: 100px;" src="files/{{$product->image}}" /></td>
          <td>{{ $product->price }} QTR</td>
          <td> 
              @if($product->is_approved == 1)
                <span class="label label-success">Active</span>
              @else
                <span class="label label-danger">Disabled</span>
              @endif
            </td>
          <td>{{ $product->stock_available }}</td>
          <td>{{ $product->category }}</td>
          <td>
            <form id="delete-form-{{$product->id}}" action="{{ route('products.destroy',$product->id) }}" method="POST">
              <a class="btn btn-info" href="{{ route('products.show',$product->id) }}">Show</a>
              <a class="btn btn-primary" href="{{ route('products.edit',$product->id) }}">Edit</a>
              @csrf
              @method('DELETE')
              {{--  <button type="submit" class="btn btn-danger">Delete</button>  --}}
              <button type="button" onclick="ask_delete({{$product->id}})" class="btn btn-danger">Delete</button>
              

            </form>
          </td>
        </tr>
        @endforeach
        </tbody>
    </table>

    {{--  {{$products->links()}}  --}}




    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>

    <script>
      $("#current-files").sortable({
        connectWith: "#selected-files",
        update: function(event, ui) { 
            var newIndex = ui.item.index();
            var obj = [];
            $('#current-files tr').each(function() {
                obj.push(this.id)
              })
              
              $.ajax({
                  url: "/update-product-order",
                  method: 'POST',
                  data:{
                    ids : obj,
                    _token: document.getElementsByName("_token")[0].value
                  },
                  success: function(res){
                      index = 0;
                      items = document.getElementsByClassName('index-td');
                      for(i = 0; i <= items.length; i++){
                          console.log(i)
                            $(items[i]).html(i+1) 
                      }
                  }
              });
        },
        
        start: function(event, ui) { 
            console.log('start: ' + ui.item.index())
        }
    });
    $("#selected-files").sortable();

    
    </script>

    @endsection

resources/views/products/show.blade.php
@extends('products.layout')

@section('content')

<style>
    .image-container{
        display: inline;
        position: relative;
    }
    .image-container .btn{
        position: absolute ;
        top: -70px;
        right: 0;
        border-radius: 50%;
        background-color: white;
        color: black;
        padding: 4px 10px !important
    }
    .video-container {
        position: relative;
        display: inline;
  
    }
     .video-container .btn{
        position: absolute ;
        top: -150;
        right: 0;
        border-radius: 50%;
        background-color: #c8c8c8;
  
    }
    
    .image-container .btn:hover{
        background-color: #c8c8c8;
        color: #fff;
  
    }
    
    .video-container .btn:hover{
        background-color: #c8c8c8;
        color: #fff;
  
    }
  
    .image-preview-tag{
      width: 130px;
      height: 130px;
      border-radius: 4%;
  
    }
  </style>
  
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Products</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $product->name }}<br>
                <strong>Arabic Name:</strong>
                {{ $product->arabic_name }}<br>
                <strong>Description:</strong>
                {{ $product->description }}<br>
                <strong>Arabic Description:</strong>
                {{ $product->description_ar }}<br>
                <strong>Price:</strong>
                {{ $product->price }} QTR<br>
                <strong>Available Stock:</strong>
                {{ $product->stock_available }}<br>
                <strong>Category:</strong>
                {{ $product->category }}<br>
                <strong>Images:</strong>
                <?php $path= '/files/'. $product->image; ?>
                {{-- <img style="width:100px;height: 100px;" src="<?= $path ?>" /><br> --}}

                <div class="col-xs-12 col-sm-12 col-md-12" >
                    <input type="file" name="images[]" style="display: none" multiple id="gallery-photo-add">
                    <div class="gallery" id="image-preview" >
                      @if( $product->images && is_array(json_decode($product->images)))
                      @foreach(json_decode($product->images) as $k => $image )
                      <div class="image-container" id="image-{{$k}}" >
                      <img src="{{asset('files/'.$image)}} "  class="m-2 image-preview-tag" > 
                      </div>
                      @endforeach
                      @endif
                    </div>
              </div>

            </div>
        </div>
    </div>
@endsection